import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/Banner'
const inter = Inter({ subsets: ['latin'] })
const handlebuttonClick = () => {
  console.log('button clicked')
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Get coffe houses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <ul className={styles.header}>
            <li>
              <a href="#">Home</a>
              </li>
            <li>
              <a href="#">About</a>
              </li>
            <li>
              <a href="#">Contact</a>
              </li>

          </ul>
          <div>
            <h1 className={styles.title}>
              Login
              </h1>
          </div>
        </div>
        <div className={styles.hero}>
          <Banner buttonText="Views stores Nearby" handleClick={handlebuttonClick}/>
        <div>
          <Image src="/static/hero.svg" width={700} height={400} />
        </div>
        </div>

        <div className={styles.center}>
          
        </div>

        <div className={styles.grid}>
         
        </div>

      </main>
    </>
  )
}
